
                (function() {
                    var nodeEnv = typeof require !== 'undefined' && typeof process !== 'undefined';
                    var __module = nodeEnv ? module : {exports:{}};
                    var __filename = 'preview-scripts/assets/TmoDemo/Script/TmoGame.js';
                    var __require = nodeEnv ? function (request) {
                        return cc.require(request);
                    } : function (request) {
                        return __quick_compile_project__.require(request, __filename);
                    };
                    function __define (exports, require, module) {
                        if (!nodeEnv) {__quick_compile_project__.registerModule(__filename, module);}"use strict";
cc._RF.push(module, '0d96eU/lZVHW4W4yuZIhrlV', 'TmoGame');
// TmoDemo/Script/TmoGame.js

"use strict";

// Learn cc.Class:
//  - https://docs.cocos.com/creator/manual/en/scripting/class.html
// Learn Attribute:
//  - https://docs.cocos.com/creator/manual/en/scripting/reference/attributes.html
// Learn life-cycle callbacks:
//  - https://docs.cocos.com/creator/manual/en/scripting/life-cycle-callbacks.html
cc.Class({
  "extends": cc.Component,
  properties: {
    tiledMapAfter: cc.TiledMap,
    tiledMapOrigin: cc.TiledMap
  },
  start: function start() {
    window.game = this;
    var isAfter = true; // var isAfter = false;

    if (isAfter) {
      this.tiledMapOrigin.node.active = false;
    } else {
      this.tiledMapAfter.node.active = false;
    }

    this.addTimeLog();
  },
  addTimeLog: function addTimeLog() {
    var renderCount = 1;
    cc.director.on(cc.Director.EVENT_BEFORE_DRAW, function () {
      if (renderCount < 200) {
        console.time("render");
      }
    });
    cc.director.on(cc.Director.EVENT_AFTER_DRAW, function () {
      if (renderCount++ < 200) {
        console.timeEnd("render");
      }
    }); // cc.director.on(cc.Director.EVENT_BEFORE_UPDATE, ()=>{
    //     if (renderCount < 200) {
    //         console.time("logic");
    //     }
    // });
    // cc.director.on(cc.Director.EVENT_AFTER_UPDATE, ()=>{
    //     if (renderCount++ < 200) {
    //         console.timeEnd("logic");
    //     }
    // });
  }
});

cc._RF.pop();
                    }
                    if (nodeEnv) {
                        __define(__module.exports, __require, __module);
                    }
                    else {
                        __quick_compile_project__.registerModuleFunc(__filename, function () {
                            __define(__module.exports, __require, __module);
                        });
                    }
                })();
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImFzc2V0c1xcVG1vRGVtb1xcU2NyaXB0XFxUbW9HYW1lLmpzIl0sIm5hbWVzIjpbImNjIiwiQ2xhc3MiLCJDb21wb25lbnQiLCJwcm9wZXJ0aWVzIiwidGlsZWRNYXBBZnRlciIsIlRpbGVkTWFwIiwidGlsZWRNYXBPcmlnaW4iLCJzdGFydCIsIndpbmRvdyIsImdhbWUiLCJpc0FmdGVyIiwibm9kZSIsImFjdGl2ZSIsImFkZFRpbWVMb2ciLCJyZW5kZXJDb3VudCIsImRpcmVjdG9yIiwib24iLCJEaXJlY3RvciIsIkVWRU5UX0JFRk9SRV9EUkFXIiwiY29uc29sZSIsInRpbWUiLCJFVkVOVF9BRlRFUl9EUkFXIiwidGltZUVuZCJdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFFQUEsRUFBRSxDQUFDQyxLQUFILENBQVM7QUFDTCxhQUFTRCxFQUFFLENBQUNFLFNBRFA7QUFHTEMsRUFBQUEsVUFBVSxFQUFFO0FBQ1JDLElBQUFBLGFBQWEsRUFBRUosRUFBRSxDQUFDSyxRQURWO0FBRVJDLElBQUFBLGNBQWMsRUFBRU4sRUFBRSxDQUFDSztBQUZYLEdBSFA7QUFRTEUsRUFBQUEsS0FSSyxtQkFRSTtBQUNMQyxJQUFBQSxNQUFNLENBQUNDLElBQVAsR0FBYyxJQUFkO0FBQ0EsUUFBSUMsT0FBTyxHQUFHLElBQWQsQ0FGSyxDQUdMOztBQUVBLFFBQUlBLE9BQUosRUFBYTtBQUNULFdBQUtKLGNBQUwsQ0FBb0JLLElBQXBCLENBQXlCQyxNQUF6QixHQUFrQyxLQUFsQztBQUNILEtBRkQsTUFFTztBQUNILFdBQUtSLGFBQUwsQ0FBbUJPLElBQW5CLENBQXdCQyxNQUF4QixHQUFpQyxLQUFqQztBQUNIOztBQUVELFNBQUtDLFVBQUw7QUFDSCxHQXBCSTtBQXNCTEEsRUFBQUEsVUF0Qkssd0JBc0JTO0FBQ1YsUUFBSUMsV0FBVyxHQUFHLENBQWxCO0FBQ0FkLElBQUFBLEVBQUUsQ0FBQ2UsUUFBSCxDQUFZQyxFQUFaLENBQWVoQixFQUFFLENBQUNpQixRQUFILENBQVlDLGlCQUEzQixFQUE4QyxZQUFJO0FBQzlDLFVBQUlKLFdBQVcsR0FBRyxHQUFsQixFQUF1QjtBQUNuQkssUUFBQUEsT0FBTyxDQUFDQyxJQUFSLENBQWEsUUFBYjtBQUNIO0FBQ0osS0FKRDtBQU1BcEIsSUFBQUEsRUFBRSxDQUFDZSxRQUFILENBQVlDLEVBQVosQ0FBZWhCLEVBQUUsQ0FBQ2lCLFFBQUgsQ0FBWUksZ0JBQTNCLEVBQTZDLFlBQUk7QUFDN0MsVUFBSVAsV0FBVyxLQUFLLEdBQXBCLEVBQXlCO0FBQ3JCSyxRQUFBQSxPQUFPLENBQUNHLE9BQVIsQ0FBZ0IsUUFBaEI7QUFDSDtBQUNKLEtBSkQsRUFSVSxDQWVWO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0g7QUFoREksQ0FBVCIsInNvdXJjZVJvb3QiOiIvIiwic291cmNlc0NvbnRlbnQiOlsiLy8gTGVhcm4gY2MuQ2xhc3M6XHJcbi8vICAtIGh0dHBzOi8vZG9jcy5jb2Nvcy5jb20vY3JlYXRvci9tYW51YWwvZW4vc2NyaXB0aW5nL2NsYXNzLmh0bWxcclxuLy8gTGVhcm4gQXR0cmlidXRlOlxyXG4vLyAgLSBodHRwczovL2RvY3MuY29jb3MuY29tL2NyZWF0b3IvbWFudWFsL2VuL3NjcmlwdGluZy9yZWZlcmVuY2UvYXR0cmlidXRlcy5odG1sXHJcbi8vIExlYXJuIGxpZmUtY3ljbGUgY2FsbGJhY2tzOlxyXG4vLyAgLSBodHRwczovL2RvY3MuY29jb3MuY29tL2NyZWF0b3IvbWFudWFsL2VuL3NjcmlwdGluZy9saWZlLWN5Y2xlLWNhbGxiYWNrcy5odG1sXHJcblxyXG5jYy5DbGFzcyh7XHJcbiAgICBleHRlbmRzOiBjYy5Db21wb25lbnQsXHJcblxyXG4gICAgcHJvcGVydGllczoge1xyXG4gICAgICAgIHRpbGVkTWFwQWZ0ZXI6IGNjLlRpbGVkTWFwLFxyXG4gICAgICAgIHRpbGVkTWFwT3JpZ2luOiBjYy5UaWxlZE1hcCxcclxuICAgIH0sXHJcblxyXG4gICAgc3RhcnQgKCkge1xyXG4gICAgICAgIHdpbmRvdy5nYW1lID0gdGhpcztcclxuICAgICAgICB2YXIgaXNBZnRlciA9IHRydWU7XHJcbiAgICAgICAgLy8gdmFyIGlzQWZ0ZXIgPSBmYWxzZTtcclxuXHJcbiAgICAgICAgaWYgKGlzQWZ0ZXIpIHtcclxuICAgICAgICAgICAgdGhpcy50aWxlZE1hcE9yaWdpbi5ub2RlLmFjdGl2ZSA9IGZhbHNlO1xyXG4gICAgICAgIH0gZWxzZSB7XHJcbiAgICAgICAgICAgIHRoaXMudGlsZWRNYXBBZnRlci5ub2RlLmFjdGl2ZSA9IGZhbHNlO1xyXG4gICAgICAgIH1cclxuXHJcbiAgICAgICAgdGhpcy5hZGRUaW1lTG9nKCk7XHJcbiAgICB9LFxyXG5cclxuICAgIGFkZFRpbWVMb2cgKCkge1xyXG4gICAgICAgIGxldCByZW5kZXJDb3VudCA9IDE7XHJcbiAgICAgICAgY2MuZGlyZWN0b3Iub24oY2MuRGlyZWN0b3IuRVZFTlRfQkVGT1JFX0RSQVcsICgpPT57XHJcbiAgICAgICAgICAgIGlmIChyZW5kZXJDb3VudCA8IDIwMCkge1xyXG4gICAgICAgICAgICAgICAgY29uc29sZS50aW1lKFwicmVuZGVyXCIpO1xyXG4gICAgICAgICAgICB9XHJcbiAgICAgICAgfSk7XHJcbiAgICBcclxuICAgICAgICBjYy5kaXJlY3Rvci5vbihjYy5EaXJlY3Rvci5FVkVOVF9BRlRFUl9EUkFXLCAoKT0+e1xyXG4gICAgICAgICAgICBpZiAocmVuZGVyQ291bnQrKyA8IDIwMCkge1xyXG4gICAgICAgICAgICAgICAgY29uc29sZS50aW1lRW5kKFwicmVuZGVyXCIpO1xyXG4gICAgICAgICAgICB9XHJcbiAgICAgICAgfSk7XHJcblxyXG5cclxuICAgICAgICAvLyBjYy5kaXJlY3Rvci5vbihjYy5EaXJlY3Rvci5FVkVOVF9CRUZPUkVfVVBEQVRFLCAoKT0+e1xyXG4gICAgICAgIC8vICAgICBpZiAocmVuZGVyQ291bnQgPCAyMDApIHtcclxuICAgICAgICAvLyAgICAgICAgIGNvbnNvbGUudGltZShcImxvZ2ljXCIpO1xyXG4gICAgICAgIC8vICAgICB9XHJcbiAgICAgICAgLy8gfSk7XHJcbiAgICBcclxuICAgICAgICAvLyBjYy5kaXJlY3Rvci5vbihjYy5EaXJlY3Rvci5FVkVOVF9BRlRFUl9VUERBVEUsICgpPT57XHJcbiAgICAgICAgLy8gICAgIGlmIChyZW5kZXJDb3VudCsrIDwgMjAwKSB7XHJcbiAgICAgICAgLy8gICAgICAgICBjb25zb2xlLnRpbWVFbmQoXCJsb2dpY1wiKTtcclxuICAgICAgICAvLyAgICAgfVxyXG4gICAgICAgIC8vIH0pO1xyXG4gICAgfSxcclxuXHJcbn0pO1xyXG4iXX0=